server:
  port: 8080

spring:
  application:
    name: oauth2-server
  
  ldap:
    urls: ldap://localhost:1389
    base: dc=example,dc=com
    username: cn=admin,dc=example,dc=com
    password: admin
    base-environment-properties:
      java.naming.ldap.attributes.binary: objectGUID
  
  security:
    oauth2:
      authorization-server:
        client:
          client1:
            registration:
              client-id: client1
              client-secret: "{noop}secret1"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:3000/callback"
              scopes:
                - "read"
                - "write"
                - "user"
            provider:
              issuer-uri: "http://localhost:8080"
          client2:
            registration:
              client-id: client2
              client-secret: "{noop}secret2"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "client_credentials"
              scopes:
                - "read"
                - "write"
                - "api"
            provider:
              issuer-uri: "http://localhost:8080"

# JWT Configuration
jwt:
  secret: your-256-bit-secret-key-here-make-it-long-and-secure
  expiration: 86400000 # 24 hours in milliseconds

# Swagger UI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
  packages-to-scan: com.example.oauth2server.controller

# Logging
logging:
  level:
    org.springframework.security: DEBUG
    com.example.oauth2server: DEBUG



